# Generated by Django 4.1.3 on 2022-11-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_alter_team_team_end'),
        ('team_roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_pace', models.TimeField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('team_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_roles.teamrole')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
