# Generated by Django 4.1.3 on 2022-11-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_race_admin',
            field=models.BooleanField(default=False, verbose_name='race admin status'),
        ),
    ]
