# Generated by Django 4.1.3 on 2022-11-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runners', '0002_rename_team_id_runner_team_and_more'),
        ('race_legs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_leg_start', models.DateTimeField()),
                ('runner_leg_end', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('race_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race_legs.raceleg')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runners.runner')),
            ],
        ),
    ]
