# Generated by Django 4.1.3 on 2022-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_legs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceleg',
            name='leg_end_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceleg',
            name='leg_end_city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceleg',
            name='leg_end_state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceleg',
            name='leg_end_zip',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
