# Generated by Django 4.1.3 on 2022-11-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=500)),
                ('race_start_date', models.DateField()),
                ('race_finish_opens', models.DateTimeField()),
                ('race_finish_closes', models.DateTimeField()),
                ('race_start_place_id', models.CharField(max_length=500)),
            ],
        ),
    ]
