# Generated by Django 4.1.3 on 2022-11-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_end',
            field=models.DateTimeField(),
        ),
    ]
